/**
 * Zone București – listă pentru selectarea zonei când Județ = București.
 * Ordinea și grupurile sunt păstrate pentru ușurință în căutare.
 */
export const BUCHAREST_ZONES = [
  "1 Decembrie 1918",
  "1 Mai",
  "13 Septembrie",
  "16 Februarie",
  "23 August (Catelul)",
  "Alba Iulia",
  "Alexandru Obregia",
  "Alexandriei",
  "Amzei",
  "Andronache",
  "Antiaeriana",
  "Aparatorii Patriei",
  "Apusului",
  "Arcul de Triumf",
  "Armeneasca",
  "Aviatiei",
  "Aviatorilor",
  "Baba Novac",
  "Baicului",
  "Balta Alba",
  "Banu Manta",
  "Barbu Vacarescu",
  "Basarab",
  "Basarabia",
  "Batistei",
  "Bd. Gloriei",
  "Bd. Laminorului",
  "Beller",
  "Berceni",
  "Brezoianu",
  "Brancoveanu",
  "Bucur Obor",
  "Bucurestii Noi",
  "Calea Calarasilor",
  "Central",
  "Calea Plevnei",
  "Calea Victoriei",
  "Camil Ressu",
  "Campia Libertatii",
  "Candiano Popescu",
  "Cantemir",
  "Capitale",
  "Casin",
  "Centrul Civic",
  "Centrul Istoric",
  "Centura Est",
  "Centura Nord",
  "Centura Sud",
  "Chibrit",
  "Chirigii",
  "Chisinau",
  "Chitila",
  "Cismigiu",
  "Clabucet",
  "Clucerului",
  "Colentina",
  "Compozitorilor",
  "Constructorilor",
  "Cosbuc",
  "Costin Georgian",
  "Cotroceni",
  "Crangasi",
  "Cutitul de Argint",
  "Dacia",
  "Damaroaia",
  "Decebal",
  "DN 1",
  "DN 2",
  "Doamna Ghica",
  "Domenii",
  "Dorobanti",
  "Dristor",
  "Drumul Gazarului",
  "Drumul Sarii",
  "Drumul Taberei",
  "Dudesti",
  "Eminescu",
  "Eroii Revolutiei",
  "Est",
  "Ferdinand",
  "Ferentari",
  "Fizicienilor",
  "Foisorul de Foc",
  "Floreasca",
  "Fundeni",
  "Gara de Nord",
  "Gara de Est",
  "Ghencea",
  "Giulesti",
  "Giulesti Sarbi",
  "Giurgiului",
  "Gradina Icoanei",
  "Grozavesti",
  "Grivita",
  "Herastrau",
  "I.C. Bratianu",
  "Iancu Nicolae",
  "Iancului",
  "Ion Creanga",
  "Industriilor",
  "Kiseleff",
  "Kogalniceanu",
  "Lacul Tei",
  "Lacul Morii",
  "Lahovari",
  "Libertatii",
  "Lipscani",
  "Liviu Rebreanu",
  "Lizeanu",
  "Lucretiu Patrascanu",
  "Lujerului",
  "Magheru",
  "Magurele",
  "Margeanului",
  "Marasesti",
  "Matei Voievod",
  "Metalurgiei",
  "Mihai Bravu",
  "Militari",
  "Mitropolie",
  "Moinesti",
  "Morarilor",
  "Mosilor",
  "Muncii",
  "Natiunile Unite",
  "Nerva Traian",
  "Nicolae Grigorescu",
  "Nord",
  "Nordului",
  "Obor",
  "Octavian Goga",
  "Oltenitei",
  "Ozana",
  "Pache Protopopescu",
  "P-ta Alba Iulia",
  "P-ta Amzei",
  "P-ta Arsenalului",
  "P-ta de Gros",
  "P-ta Dorobanti",
  "P-ta Galati",
  "P-ta Gorjului",
  "P-ta Jose Rizal",
  "P-ta Leul",
  "P-ta Muncii",
  "P-ta Operei",
  "P-ta Presei Libere",
  "P-ta Resita",
  "P-ta Romana",
  "P-ta Rosetti",
  "P-ta Sfanta Vineri",
  "P-ta Sfantul Gheorghe",
  "P-ta Sfantul Stefan",
  "P-ta Sfintii Voievozi",
  "P-ta Unirii",
  "P-ta Universitatii",
  "P-ta Victoriei",
  "Pacii",
  "Pajura",
  "Panduri",
  "Pantelimon",
  "Parcul Carol",
  "Parcul Circului",
  "Petricani",
  "Pieptanari",
  "Pipera",
  "Plevnei",
  "Polona",
  "Politehnica",
  "Prelungirea Ferentari",
  "Prelungirea Ghencea",
  "Primaverii",
  "Progresul",
  "Rahova",
  "Regina Elisabeta",
  "Regie",
  "Romana",
  "Rosetti",
  "Salajan",
  "Salaj",
  "Sala Palatului",
  "Sebastian",
  "Serban Voda",
  "Sisesti",
  "Socului",
  "Soseaua Nordului",
  "Splaiul Independentei",
  "Splaiul Unirii",
  "Stefan cel Mare",
  "Stirbei Voda",
  "Straulesti",
  "Sud",
  "Sura Mare",
  "Take Ionescu",
  "Tei",
  "Teiul Doamnei",
  "Televiziune",
  "Theodor Pallady",
  "Timpuri Noi",
  "Tineretului",
  "Titulescu",
  "Timisoara",
  "Trafic Greu",
  "Tudor Vladimirescu",
  "Turda",
  "Ultracentral",
  "Unirii",
  "Universitate",
  "Uverturii",
  "Valea Ialomitei",
  "Valea Oltului",
  "Vasile Parvan",
  "Vatra Luminoasa",
  "Veteranilor",
  "Victoriei",
  "Viilor",
  "Vitan",
  "Vitan Mall",
  "Vitan-Barzesti",
  "Vitanul Nou",
  "Virtutii",
  "Vest",
  "Zetarilor",
] as const;

export type BucharestZone = (typeof BUCHAREST_ZONES)[number];
